# https://github.blog/changelog/2022-09-08-github-actions-use-github_token-with-workflow_dispatch-and-repository_dispatch/
name: Create Workflow Dispatch (Trigger Submodule Pull)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
      - run: | # https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
          gh workflow run github_action_update_submodules.yml -R brightway-lca/brightway-documentation
    env:
      GH_TOKEN: ${{ secrets.GHA_WORKFLOW_TRIGGER }}