name: dispatch test

on: workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.GHA_WORKFLOW_TRIGGER }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run workflow
        run: |
          gh workflow run github_action_update_submodules.yml -R brightway-lca/brightway-documentation